# -*- coding: utf-8 -*-
"""OIBSIP_Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iSjv8lcnkGkvTrkNmyaNq0nOJ0nT24ED

# **UNEMPLOYMENT ANALYSIS WITH PYTHON**

# **Import Required Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# **Load the Unemployment Dataset**"""

df = pd.read_csv("/content/Unemployment in India.csv")
df.head()

"""# **Data Exploration & Preprocessing**"""

# Check data types and non-null values
print(df.info())

#Check for Missing Values

print(df.isnull().sum())  # Count missing values in each column

#Handle missing vaues
df.ffill(inplace=True)  # Forward fill missing values

print(df.columns)  # Display all column names

df = df.rename(columns=lambda x: x.strip())

df.columns

#Convert Date Column to Proper Format
df['Date'] = pd.to_datetime(df['Date'].str.strip(), format="%d-%m-%Y")

df['Date'].head()

# Describe Statistics
print(df.describe())

#Check for Duplicates
print(f"Duplicate rows before removal: {df.duplicated().sum()}")
df.drop_duplicates(inplace=True)
print(f"Duplicate rows after removal: {df.duplicated().sum()}")

#Rename columns
df.rename(columns={'Estimated Unemployment Rate (%)': 'Unemployment Rate',
                   'Estimated Employed': 'Employed',
                   'Estimated Labour Participation Rate (%)': 'Labour Participation Rate'}, inplace=True)

df.columns

"""# **Exploratory Data Analysis (EDA)**

### **Bar Chart: Average Unemployment Rate by Region**
"""

# Group by Region and find the average unemployment rate
region_unemployment = df.groupby('Region')['Unemployment Rate'].mean().sort_values()

plt.figure(figsize=(12, 6))
sns.barplot(x=region_unemployment.index, y=region_unemployment.values,hue=region_unemployment.index, palette="dark:blue",legend=False)

plt.xlabel("Region")
plt.ylabel("Average Unemployment Rate (%)")
plt.title("Average Unemployment Rate by Region")
plt.xticks(rotation=90)
plt.show()

"""### **Scatter Plot: Unemployment Rate vs. Labour Participation Rate**"""

plt.figure(figsize=(8, 6))
sns.scatterplot(x=df['Labour Participation Rate'],
                y=df['Unemployment Rate'],
                hue=df['Area'], alpha=0.7, palette='inferno')

plt.xlabel("Labour Participation Rate (%)")
plt.ylabel("Unemployment Rate (%)")
plt.title("Unemployment Rate vs. Labour Participation Rate")
plt.legend(title="Area")
plt.show()

"""### **Pie Chart: Maximum Unemployment Rate by Area Type (Rural vs Urban)**"""

# Group by 'Area' and get max unemployment rate
area_max = df.groupby('Area')['Unemployment Rate'].max()

plt.figure(figsize=(8, 8))
plt.pie(area_max, labels=area_max.index, autopct='%1.1f%%', colors=['#ff9999','#66b3ff'])

plt.title("Maximum Unemployment Rate: Rural vs Urban")
plt.show()

"""### **Unemployment Rate Trends: Pre-COVID vs. During COVID-19 Pandemic**"""

#Ensure the Date column is in the correct format and set it as the index
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)

#Define pre-COVID and COVID periods (March 2020 as start of COVID)
df['COVID Period'] = df.index < pd.to_datetime('2020-03-01')
df['COVID Period'] = df['COVID Period'].replace({True: 'Pre-COVID', False: 'During COVID'})

#Plot Unemployment Rate Over Time with Different Styles for Pre-COVID and During COVID
plt.figure(figsize=(14, 7))

# Plot Pre-COVID with dashed line
sns.lineplot(x=df[df['COVID Period'] == 'Pre-COVID'].index,
             y=df[df['COVID Period'] == 'Pre-COVID']['Unemployment Rate'],
             marker='o', linestyle='--', color='b', label='Pre-COVID')

# Plot During COVID with solid line
sns.lineplot(x=df[df['COVID Period'] == 'During COVID'].index,
             y=df[df['COVID Period'] == 'During COVID']['Unemployment Rate'],
             marker='s', linestyle='-', color='r', label='During COVID')

#Highlight the COVID-19 start with a vertical line
plt.axvline(pd.to_datetime('2020-03-01'), color='k', linestyle=':', label="COVID-19 Start")

# Adding labels and title
plt.title('Unemployment Rate Over Time: Pre-COVID vs During COVID')
plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')
plt.legend()
plt.grid(True)
plt.show()

"""## **Correlation Heatmap**"""

correlation_matrix = df[['Unemployment Rate', 'Employed', 'Labour Participation Rate']].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Heatmap')
plt.show()

"""**Key Findings & Analysis:**

* **Unemployment's Complex Relationship**: Unemployment is linked to both the number of employed people (strongly) and labor participation (weakly). Other things also influence who's in the workforce.
* **Regional Disparities are Stark**: Massive differences in average unemployment exist across regions, suggesting local economic factors are very important. Haryana and Tripura's extremely high rates are particularly concerning.
* **Rural vs. Urban Dynamics**: The relationship between unemployment and labor participation differs in rural and urban areas. Rural areas seem more stable, while urban areas are more vulnerable.
* **COVID-19's Clear Impact**: COVID-19 caused a sharp increase in unemployment and it remained high for a considerable period, demonstrating a significant negative economic impact.










"""